version: '3'
services:
  httpd:
    build: ./httpd
    ports:
      - 8080:80
    restart: always
    networks:
      frontend:    
  tor:
    image: dperson/torproxy
    restart: always
    ports:
      - 10.10.1.1:8118:8118
      - 10.10.1.1:9050:9050
      - 192.168.189.1:8118:8118
      - 192.168.189.1:9050:9050
    environment:
      - 'LOCATION=RU'    
    networks:
      frontend:        
  squid_forward:
    image: sameersbn/squid:3.5.27-2
    volumes:
      - ./squid/forward.conf:/etc/squid/squid.conf
      - ./squid/ban_domains.txt:/etc/squid/ban_domains.txt
    restart: always
    networks:
      network-services_vlan:
      frontend:
    ports:
      - 10.10.1.1:3128:3128
    depends_on:
      - elastic
  elastic:
    restart: always
    build: ./elk
    volumes:
      - ./elk/logs:/var/lib/elasticsearch
      - ./elk/logstash.conf:/etc/logstash/conf.d/30-output.conf
    networks:
      network-services_vlan:
        ipv4_address: 10.10.1.193
    environment:
      - ES_HEAP_SIZE=8g
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:9200/_cluster/health && echo 'OK'"]
      interval: 5s
      timeout: 2s
      retries: 3      
  # syslogd:
  #   image: helder/rsyslog
  #   volumes:
  #     - ./syslog/01-json-template.conf:/etc/rsyslog.d/01-json-template.conf
  #     - ./syslog/60-output.conf:/etc/rsyslog.d/60-output.conf
  #     - ./syslog/rsyslog.conf:/etc/rsyslogd.conf
  #   networks:
  #     network-services_vlan:
  #       ipv4_address: 10.10.1.101
  #   restart: always
  squid_reverse:
    image: sameersbn/squid:3.5.27-2
    volumes:
      - ./squid/reverse.conf:/etc/squid/squid.conf
    networks:
      network-services_vlan:      
      frontend:      
    ports:
      - 8081:80
    restart: always
networks:
  network-services_vlan:
    external: true
  frontend:
