version: '2'
services:
  httpd:
    build: ./httpd
    ports:
      - 8081:80
    restart: always
    networks:
      frontend:    
  tor:
    image: dperson/torproxy
    restart: always
    ports:
      - 8118:8118
      - 9050:9050
    environment:
      - 'LOCATION=RU'    
    networks:
      frontend:        
  squid_forward:
    image: muccg/squid-deb-proxy:latest
    volumes:
      - ./squid/forward.conf:/etc/squid-deb-proxy/squid-deb-proxy.conf
    restart: always
    networks:
      backend:
      frontend:
    ports:
      - 3128:3128
    depends_on:
      - elastic
  elastic:
    build: ./elk
    volumes:
      - ./elk/logs:/var/lib/elasticsearch
      - ./elk/logstash.conf:/etc/logstash/conf.d/30-output.conf
    networks:
      backend:
        ipv4_address: 192.168.189.100
    # ports:
    #   - 5601:5601
    #   - 9200:9200
    environment:
      - ES_HEAP_SIZE=4g
      - KIBANA_START=1
      - LOGSTASH_START=1
  squid_reverse:
    image: sameersbn/squid:3.5.27-2
    volumes:
      - ./squid/reverse.conf:/etc/squid/squid.conf
    networks:
      backend:      
      frontend:      
    ports:
      - 80:80
    restart: always
networks:
  backend:
    ipam:
      config:
      - subnet: 192.168.189.0/25
  frontend:
    ipam:
      config:
      - subnet: 192.168.189.128/25
